# Ctrl-dash as prefix (works on Ghostty)
set prefix 'C--'
# Ctrl-ø as prefix (works on iTerm2)
set prefix2 'C-\'

# set foreground colour of statusline to blue
set status-style 'bg=black,fg=color26'

# vim: filetype=tmux
