-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color0 = '#f8f8f2'
local Color12 = '#939390'
local Color5 = '#66d9ef'
local Color2 = '#fd971f'
local Color3 = '#ae81ff'
local Color1 = '#f92672'
local Color6 = '#000000'
local Color7 = '#111111'
local Color8 = '#2c321e'
local Color9 = '#400d0d'
local Color4 = '#e6db74'
local Color10 = '#264f78'
local Color11 = '#808080'

highlight('Operator', nil, Color0, nil)
highlight('Keyword', nil, Color1, nil)
highlight('Identifier', nil, Color0, nil)
highlight('Function', nil, Color2, nil)
highlight('Type', nil, Color3, nil)
highlight('Conditional', nil, Color1, nil)
highlight('Repeat', nil, Color1, nil)
highlight('Type', nil, Color1, nil)
highlight('String', nil, Color4, nil)
highlight('Number', nil, Color5, nil)
highlight('Constant', nil, Color5, nil)
highlight('StatusLine', Color0, Color6, nil)
highlight('WildMenu', Color7, Color0, nil)
highlight('Pmenu', Color7, Color0, nil)
highlight('PmenuSel', Color0, Color6, nil)
highlight('PmenuThumb', Color7, Color0, nil)
highlight('DiffAdd', Color8, nil, nil)
highlight('DiffDelete', Color9, nil, nil)
highlight('Normal', Color7, Color0, nil)
highlight('Visual', Color10, nil, nil)
highlight('CursorLine', Color10, nil, nil)
highlight('ColorColumn', Color10, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color11, nil)
highlight('TabLine', Color7, Color12, nil)
highlight('TabLineSel', Color0, Color6, nil)
highlight('TabLineFill', Color7, Color12, nil)
highlight('TSPunctDelimiter', nil, Color0, nil)

link('TSParameterReference', 'TSParameter')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSField', 'Constant')
link('TSTag', 'MyTag')
link('TSOperator', 'Operator')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameter', 'Constant')
link('TSProperty', 'TSField')
link('TSRepeat', 'Repeat')
link('TSLabel', 'Type')
link('Conditional', 'Operator')
link('Repeat', 'Conditional')
link('TSFuncMacro', 'Macro')
link('TSString', 'String')
link('TSComment', 'Comment')
link('Macro', 'Function')
link('NonText', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSFunction', 'Function')
link('TSNumber', 'Number')
link('Folded', 'Comment')
link('TelescopeNormal', 'Normal')
link('TSTagDelimiter', 'Type')
link('TSConstant', 'Constant')
link('Operator', 'Keyword')
link('TSKeyword', 'Keyword')
link('TSFloat', 'Number')
link('TSNamespace', 'TSType')
link('TSPunctBracket', 'MyTag')
link('TSConditional', 'Conditional')
link('TSType', 'Type')
link('Whitespace', 'Comment')
